### ISSUE TITLE
docker 启动之后找不到接口， 这是什么错误？

### ISSUE THREAD

**Issue by VashonHu** [dairoot/CloudFlare5sBypass#2]
首先操作都是在同一台服务器上进行的
1. 
<img width="1396" alt="image" src="https://github.com/user-attachments/assets/3442a108-48c2-4bde-a99d-ed522dd8e978">
docker 服务已经启动， 显示运行在8000端口
2. 但我却找不到对应的接口： HTTPConnectionPool(host='0.0.0.0', port=8000): Max retries exceeded with url: /cloudflare5s/bypass-v2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f57e9975090>: Failed to establish a new connection: [Errno 111] Connection refused'))

**Comment by dairoot** [comment]
看Github教程
